server:
  port: 8301
spring:
  application:
    name: mall-config
  profiles:
    active: native #使用本地配置，要使用git存储改为git即可
  cloud:
    config:
      server:
        native: #本地仓库存储
          search-locations: classpath:/config/{application}
        git: #Git仓库存
          uri: https://github.com/CYH1000/mall-swarm/edit/master/mall-config.git
          username: CYH1000
          password: Aa11200401
          clone-on-start: true
          search-paths: '{application}'
